'packages/backend':
- any:
  - changed-files: ['packages/backend/**/*']

'packages/backend:test':
- any:
  - changed-files: ['packages/backend/test/**/*']

'packages/frontend':
- any:
  - changed-files: ['packages/frontend/**/*']

'packages/frontend:test':
- any:
  - changed-files: ['cypress/**/*']

'packages/sw':
- any:
  - changed-files: ['packages/sw/**/*']

'packages/misskey-js':
- any:
  - changed-files: ['packages/misskey-js/**/*']

'packages/misskey-js:test':
- any:
  - changed-files: ['packages/misskey-js/test/**/*', 'packages/misskey-js/test-d/**/*']
