# https://github.com/syuilo/misskey/blob/develop/docker-compose.yml

version: "3"

services:
  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379

  db:
    restart: always
    image: postgres:11.2-alpine
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - internal_network
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data
