version: 2

general:
  branches:
    ignore:
      - l10n_develop
      - imgbot

jobs:
  build:
    docker:
      - image: yukimochi/misskey-builder:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package caches
          keys:
            - npm-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-package-{{ checksum "package.json" }}-lock-{{ checksum "package-lock.json" }}
            - npm-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-package-{{ checksum "package.json" }}-
            - npm-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-
            - npm-v1-arch-{{ arch }}-
            - npm-v1-
      - run:
          name: Install Dependencies
          command: |
            npm install
      - save_cache:
          name: Cache npm packages
          key: npm-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-package-{{ checksum "package.json" }}-lock-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Configure
          command: |
            cp .travis/default.yml .config
            cp .travis/test.yml .config
      - run:
          name: Build Webpack
          command: |
            npm run build

workflows:
  version: 2
  build:
    jobs:
      - build
