version: 2.1

general:
  branches:
    ignore:
      - l10n_develop
      - imgbot

executors:
  default:
    parallelism: 4
    working_directory: /tmp/workspace
    docker:
      - image: misskey/ci:latest
      - image: circleci/mongo:latest
      - image: circleci/redis:latest

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package caches
          keys:
            - npm-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-package-{{ checksum "package.json" }}-lock-{{ checksum "package-lock.json" }}
            - npm-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-package-{{ checksum "package.json" }}-
            - npm-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-
            - npm-v1-arch-{{ arch }}-
            - npm-v1-
      - run:
          name: Install Dependencies
          command: |
            npm install
      - save_cache:
          name: Cache npm packages
          key: npm-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-package-{{ checksum "package.json" }}-lock-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Configure
          command: |
            cp .ci/default.yml .config
            cp .ci/test.yml .config
      - run:
          name: Build
          command: |
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    parameters:
      without_redis:
        type: string
        default: ""
    executor: default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - when:
          condition: <<parameters.without_redis>>
          steps:
            - run:
                name: Configure
                command: |
                  mv .config/test.yml .config/test_redis.yml
                  touch .config/test.yml
                  cat .config/test_redis.yml | while IFS= read line; do if [[ "$line" = '# __REDIS__' ]]; then break; else echo "$line" >> .config/test.yml; fi; done
      - run:
          name: Test
          command: |
            npm run test
      - when:
          condition: <<parameters.without_redis>>
          steps:
            - run:
                name: Restore
                command: |
                  rm .config/test.yml
                  mv .config/test_redis.yml .config/test.yml

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - test:
          without_redis: "true"
          requires:
            - build
