name: NyaOne Docker Build
on:
  push:
    branches:
      - 'nyaone'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/nyaone/misskey:latest

      - name: Send success webhook
        run: curl ${{ secrets.DOCKER_BUILD_SUCCESS_WEBHOOK }}?subject=%E5%96%B5%E7%AA%9D%20Misskey%20%E9%95%9C%E5%83%8F
