# this name is used in report-api-diff.yml so be careful when change name
name: Get api.json from Misskey

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  get-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [20.5.1]

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        repository: ${{ github.event.pull_request.base.repo.full_name }}
        ref: ${{ github.base_ref }}
        submodules: true
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy Configure
      run: cp .config/example.yml .config/default.yml
    - name: Build
      run: pnpm build
    - name: Generate API JSON
      run: pnpm --filter backend generate-api-json
    - name: Copy API.json
      run: cp packages/backend/built/api.json api-base.json
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-artifact
        path: api-base.json

  get-head:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [20.5.1]

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}
        submodules: true
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy Configure
      run: cp .config/example.yml .config/default.yml
    - name: Build
      run: pnpm build
    - name: Generate API JSON
      run: pnpm --filter backend generate-api-json
    - name: Copy API.json
      run: cp packages/backend/built/api.json api-head.json
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: api-artifact
        path: api-head.json

  save-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "$PR_NUMBER" > ./pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: api-artifact
          path: pr_number
