name: Storybook

on:
  push:
    branches-ignore:
      - l10n_develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
        submodules: true
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Build misskey-js
      run: pnpm --filter misskey-js build
    - name: Build storybook
      run: pnpm --filter frontend build-storybook
      env:
        NODE_OPTIONS: "--max_old_space_size=7168"
    - name: Publish to Chromatic
      id: chromatic
      uses: chromaui/action@v1
      with:
        debug: true
        exitOnceUploaded: true
        externals: |
          - "assets/**"
          - "fluent-emojis/**"
          - "locales/**"
          - "misskey-assets/**"
          - "packages/frontend/assets/**"
          - "packages/frontend/public/**"
        onlyChanged: "!(master)"
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        storybookBaseDir: packages/frontend
        traceChanged: extended
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: storybook
        path: packages/frontend/storybook-static
