name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  mocha:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [16.x]

    steps:
    - uses: ./.github/workflows/install-and-build@v1
      with:
        node_version: ${{ matrix.node_version }}
        postgres_tag: '13'
        redis_tag: '6'
    - name: Test
      run: yarn mocha

  e2e:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node_version: [16.x]
        browser: [chrome]

    steps:
    - uses: ./.github/workflows/install-and-build@v1
      with:
        node_version: ${{ matrix.node_version }}
        postgres_tag: '13'
        redis_tag: '6'
    # https://github.com/cypress-io/cypress-docker-images/issues/150
    #- name: Install mplayer for FireFox
    #  run: sudo apt install mplayer -y
    #  if: ${{ matrix.browser == 'firefox' }}
    #- uses: browser-actions/setup-firefox@latest
    #  if: ${{ matrix.browser == 'firefox' }}
    # https://github.com/cypress-io/cypress/issues/4351#issuecomment-559489091
    - name: ALSA Env
      run: echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        install: false
        start: npm run start:test
        wait-on: 'http://localhost:61812'
        headless: false
        browser: ${{ matrix.browser }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ matrix.browser }}-cypress-screenshots
        path: cypress/screenshots
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ matrix.browser }}-cypress-videos
        path: cypress/videos
